edition = "Edition2018"
wrap_comments = true
condense_wildcard_suffixes = true
format_macro_matchers = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true