program = (expression ";")*;

expression = assignment | if | disjunction;

assignment = "let" identifier "=" expression;
if = "if" expression "then" expression ("else" expression)?;

disjunction = conjunction ("or" conjunction)*;
conjunction = equality ("and" equality)*;
equality = comparison ("==" | "!=") comparison;
comparison = addition (">" | ">=" | "<" | "<=") addition;
addition = multi8n (("+" | "-") multi8n)*;
multi8n = unary (("*" | "/") unary)*;
unary = ("!" | "-") unary | primary;
primary = number | boolean | string | nil | identifier | "(" expression ")" | "{" program "}";